import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import './style.css';
type User={id:string;name:string;email:string};type Tx={id:string;from:{id:string;name:string};to:{id:string;name:string};amount:number;createdAt:string};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n/100);
function App(){const [token,setToken]=useState(sessionStorage.getItem('wallet_token')||'');const [me,setMe]=useState<User|null>(JSON.parse(sessionStorage.getItem('wallet_user')||'null'));const[email,setEmail]=useState('asha@example.com');const[password,setPassword]=useState('password123');const[balance,setBalance]=useState(0);const[users,setUsers]=useState<User[]>([]);const[txs,setTxs]=useState<Tx[]>([]);const[to,setTo]=useState('');const[amount,setAmount]=useState('500');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[pending,setPending]=useState<{toUserId:string;amount:number;key:string}|null>(null);
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});const d=await r.json().catch(()=>({error:'Unexpected server response'}));if(!r.ok)throw Error(d.error||'Request failed');return d as T}
async function refresh(){const [w,u,t]=await Promise.all([api<{balance:number}>('/wallet'),api<User[]>('/users'),api<Tx[]>('/transactions')]);setBalance(w.balance);setUsers(u);setTxs(t);setTo(prev=>u.some(x=>x.id===prev)?prev:(u[0]?.id||''))}
useEffect(()=>{if(token)refresh().catch(e=>setMessage(e.message))},[token]);
async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await api<{token:string;user:User}>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem('wallet_token',r.token);sessionStorage.setItem('wallet_user',JSON.stringify(r.user));setMe(r.user);setToken(r.token)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
async function transfer(e:React.FormEvent){e.preventDefault();const paise=Math.round(Number(amount)*100);if(!Number.isFinite(Number(amount))||Math.abs(Number(amount)*100-paise)>0.00001){setMessage('Use at most two decimal places');return}const request=pending&&pending.toUserId===to&&pending.amount===paise?pending:{toUserId:to,amount:paise,key:crypto.randomUUID()};setPending(request);setBusy(true);setMessage('');try{await api('/wallet/transfer',{method:'POST',headers:{'Idempotency-Key':request.key},body:JSON.stringify({toUserId:request.toUserId,amount:request.amount})});setPending(null);await refresh();setMessage('Transfer successful!')}catch(e){setMessage((e as Error).message+' — retry will use the same key')}finally{setBusy(false)}}
function logout(){sessionStorage.clear();setToken('');setMe(null);setMessage('');setPending(null)}
return <><header><div className="brand"><span>▣</span> pocket</div>{me&&<div>Hi, {me.name} <button className="light" onClick={logout}>Log out</button></div>}</header><main>{!token?<section className="login card"><small>JSTACK ENGINEERING ASSESSMENT · FS-01</small><h1>Your money, moving simply.</h1><p className="muted">Sign in to your seeded test wallet.</p><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>Sign in</button></form><p className="muted">Demo: asha@example.com / password123</p>{message&&<div className="notice" role="alert">{message}</div>}</section>:<><div className="hero"><small>YOUR WALLET OVERVIEW</small><h1>Welcome, {me?.name}.</h1><p>Send test money to your contacts.</p></div>{message&&<div className="notice" role="status">{message}</div>}<div className="layout"><div className="stack"><section className="card"><small>Available balance</small><div className="balance">{money(balance)}</div><small>INR · Test balance, not real bank funds</small></section><section className="card"><h2>Send money ↗</h2><form onSubmit={transfer}><label>Receiver<select value={to} onChange={e=>{setTo(e.target.value);setPending(null)}}>{users.map(u=><option key={u.id} value={u.id}>{u.name} — {u.email}</option>)}</select></label><label>Amount (INR)<input type="number" value={amount} onChange={e=>{setAmount(e.target.value);setPending(null)}} min="1" max="50000" step="0.01" required/></label><button disabled={busy||!to}>Send money</button></form><p className="muted">Duplicate-transfer protection enabled</p></section></div><section className="card"><h2>Recent activity</h2>{txs.length===0?<p className="muted">No transactions yet.</p>:txs.map(t=>{const sent=t.from.id===me?.id;return <div className="tx" key={t.id}><div><strong>{sent?'Sent to '+t.to.name:'Received from '+t.from.name}</strong><small>{new Date(t.createdAt).toLocaleString('en-IN')}</small></div><strong className={sent?'out':'in'}>{sent?'−':'+'}{money(t.amount)}</strong></div>})}</section></div></>}</main><footer>jStack · FS-01 P2P Wallet Transfer · Integer paise · Test money only</footer></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
